services:
  - type: web
    name: redapple-crackers
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: redapple-crackers.onrender.com
      - key: DATABASE_URL
        value: YOUR_EXISTING_DATABASE_URL_HERE


