# Generated by Django 6.0.7 on 2026-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
